iam = "Hello! I am"
comment = "utterances"
timeformat = "2006-01-12"
switch = ["ğŸŒš", "ğŸŒ"]
displayDate = true
selectable = true
commentOnAllPosts = true
toc = "lines"

[params.utterances]
repo = "carlosonunez/watercooler.blog.carlosnunez.me"
issueTerm = "pathname"

[[params.social]]
name = "github"
url = "https://github.com/{{ .Env.GITHUB_HANDLE }}"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/{{ .Env.LINKEDIN_HANDLE }}"
svg = ""
[[params.social]]
name = "twitter"
url = "https://twitter.com/{{ .Env.TWITTER_HANDLE }}"
svg = ""
[[params.social]]
name = "rss"
url = "/index.xml"
svg = ""
